### ISSUE TITLE
Nuxt fatal error

### ISSUE THREAD

**Issue by Barlium** [aymaneMx/nuxt-portfolio-dev#143]
Hi,

after running yarn dev, I get the following error:

yarn run v1.22.19
$ nuxt

 WARN                                                                                                         19:04:44

 WARN  warn - The purge/content options have changed in Tailwind CSS v3.0.                                    19:04:44

 WARN  warn - Update your configuration file to eliminate this warning.                                       19:04:44

 WARN  warn - https://tailwindcss.com/docs/upgrade-guide#configure-content-sources                            19:04:44

i Using default Tailwind CSS file from runtime/tailwind.css                                  nuxt:tailwindcss 19:04:44

 FATAL  Cannot destructure property 'nuxt' of 'this' as it is undefined.                                      19:04:44

  at postcss8Module (node_modules\@nuxt\postcss8\dist\index.js:15:10)
  at installModule (.../node_modules/@nuxt/kit/dist/index.mjs:435:21)
  at async setup (.../node_modules/@nuxtjs/tailwindcss/dist/module.mjs:293:7)
  at async ModuleContainer.normalizedModule (.../node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:239:20)
  at async ModuleContainer.ready (node_modules\@nuxt\core\dist\core.js:51:7)
  at async Nuxt._init (node_modules\@nuxt\core\dist\core.js:478:5)

   ╭─────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                 │
   │   ✖ Nuxt Fatal Error                                                            │
   │                                                                                 │
   │   TypeError: Cannot destructure property 'nuxt' of 'this' as it is undefined.   │
   │                                                                                 │
   ╰─────────────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Any idea how to fix this? I did try @nuxt/kit to package.json manually, as shown here: https://github.com/nuxt-modules/tailwindcss/issues/598

**Comment by Milksheyke** [comment]
Same issue :(

**Comment by mooncat126** [comment]
Same issue :(

**Comment by Foddie2** [comment]
Still having issue on this. Any solutions team?

**Comment by Dev-R** [comment]
If anyone is facing the above error, check the following fork: https://github.com/Dev-R/portfolio-and-notion-blog-with-nuxt-3

**Comment by aymaneMx** [comment]
@Dev-R Thanks for sharing the fork link to address the error. We appreciate your input! If you're open to it, we'd welcome a pull request with your solution. This would help us review and incorporate your contribution directly into the main project.

Let us know if you're interested or need any assistance with the process.
